version: 2

builds:
  - id: goload
    binary: goload
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

dockers_v2:
  - id: goload-docker
    
    dockerfile: Dockerfile.goreleaser
    
    ids:
      - goload
    
    images:
      - "ghcr.io/rafaelbreno/goload"
    
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "{{ .ShortCommit }}"
    
    platforms:
      - linux/amd64
      - linux/arm64
    
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "CLI tool for HTTP load testing"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
